### ISSUE TITLE
Custom project dir doesn't upload analyzer-result.yml

### ISSUE THREAD

**Issue by boris-bojic-pid** [porscheofficial/.github#8]
In our workflow we've defined a custom directory for the scan:

```
      - name: Pull and run OSO ORT Analyzer
        uses: porscheofficial/.github/workflows/ort-analyze@main
        with:
          ort-aws-access-key-id: ${{ env.OSO_CREDENTIALS_ACCESS_KEY_ID }}
          ort-aws-secret-access-key: ${{ env.OSO_CREDENTIALS_SECRET_ACCESS_KEY }}
          container-registry: 936427553375.dkr.ecr.eu-central-1.amazonaws.com
          container-repository: ort
          container-image-tag: latest
          allow-dynamic-versions: true
          project-dir: ./ui
```

It works so far, but the action's artifact upload won't find the analyzer-result.yml accordingly:

```
Wrote analyzer result to '/project/ort/analyzer-result.yml' (0.08 MiB) in 876.947308ms.
The analysis took 8m 55.378887897s.

...


Run actions/upload-artifact@v4
  with:
    name: ort-analyzer-result
    path: ort/analyzer-result.yml
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
    include-hidden-files: false
...
Warning: No files were found with the provided path: ort/analyzer-result.yml. No artifacts will be uploaded.

```

To solve this we need a custom upload-artifact step afterwards as a quick solution, but it would be nice to have this resolved within your action. :)
